### ISSUE TITLE
Specify the exact version of Calibre when installing

### ISSUE THREAD

**Issue by adamniedzielski** [kiskolabs/heroku-buidpack-calibre#1]
Thank your for creating this builpack - it helped me a lot!

What do you think about an option to specify the exact version of Calibre which should be installed? When using this buildpack Calibre is installed from scratch on every deploy and as a new version of Calibre is released, it will be automatically "upgraded".

It looks like the `linux-installer.py` provides a way to install a different version than the latest one - https://github.com/kovidgoyal/calibre/blob/0cb677fb90f2302a3b8fea48b60b946207f429b2/setup/linux-installer.py#L16 We could set `CALIBRE_INSTALLER_LOCAL_URL` to `http://download.calibre-ebook.com/2.62.0/calibre-2.62.0-x86_64.txz` (for example).

The value of `CALIBRE_INSTALLER_LOCAL_URL` could be read from Heroku config variables as described here https://devcenter.heroku.com/articles/buildpack-api#buildpack-api -> `ENV_DIR`.

**Comment by matiaskorhonen** [comment]
Sounds like a great idea, would you be interested in submitting this as a PR?

**Comment by matiaskorhonen** [comment]
Actually, is it enough if you just set `CALIBRE_INSTALLER_LOCAL_URL` with `heroku config:set CALIBRE_INSTALLER_LOCAL_URL="..."`?

**Comment by adamniedzielski** [comment]
@matiaskorhonen Thank you for your response! I'm no longer involved in the project where I used `heroku-buildpack-calibre` so I cannot check it 😞.
