### ISSUE TITLE
Calibre is not added to the path

### ISSUE THREAD

**Issue by adamniedzielski** [kiskolabs/heroku-buidpack-calibre#2]
I think that this line https://github.com/kiskolabs/heroku-buildpack-calibre/blob/d1473d9faee92d659f9304a07aef27d08c8bf163/bin/compile#L27 is not working as expected.

After executing:

```
heroku run /bin/bash
echo $PATH
```

I get `/usr/local/bin:/usr/bin:/bin` (no `/app/calibre`).

I think the proper way to add something to the path is shown here https://github.com/heroku/heroku-buildpack-php/blob/cd2d13992b72d049aa270d4b745aae6329e0c037/bin/compile#L115  and described here https://devcenter.heroku.com/articles/buildpack-api#example-profile-d-mybuildpack-defaults-sh

**Comment by matiaskorhonen** [comment]
Yeah, I think you're right.

Would you mind dropping this into a pull request too?
